from _typeshed import Incomplete
from buscador_de_cosas import buscador_de_cosas
from maya.app.general import mayaMixin

class BuscadorDeCosa(mayaMixin.MayaQWidgetDockableMixin, buscador_de_cosas.BuscadorDeCosaMenos):
    def __init__(self, parent: Incomplete | None = ...) -> None: ...
    @classmethod
    def deleteInstances(cls) -> None: ...
    def show(self) -> None: ...
    @staticmethod
    def get_workspace_name(widget: QtWidgets.QWidget) -> str: ...
    def dock_to_panel(self) -> None: ...

def main() -> None: ...
