import typing

from Qt import QtWidgets


def get_style_sheet(widget: typing.Any) -> str: ...
def set_style_sheet(widget: typing.Any, style_sheet: str) -> bool: ...
def collect_ancestor_stylesheets(widget: typing.Optional[QtWidgets.QWidget]) -> typing.List[typing.Tuple[QtWidgets.QWidget, str]]: ...
def format_ancestor_stylesheet(entries: typing.List[typing.Tuple[QtWidgets.QWidget, str]]) -> str: ...
