import typing

from Qt import QtCore, QtGui, QtWidgets


class PillSwitch(QtWidgets.QPushButton):
    knob_position: float
    def __init__(self, text: str = '', uses_highlight: bool = True, parent: typing.Optional[QtWidgets.QWidget] = None) -> None: ...
    def sizeHint(self) -> QtCore.QSize: ...
    def hitButton(self, position: QtCore.QPoint) -> bool: ...
    def paintEvent(self, event: QtGui.QPaintEvent) -> None: ...
